version: "3.3"
services:

  backend:
    image: $CI_REGISTRY_IMAGE/sausage-backend:${BACKEND_VERSION}
    container_name: sausage-store-backend
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - sausage-store

  backend-report:
    image: $CI_REGISTRY_IMAGE/sausage-backend-report:${BACKEND_REPORT_VERSION}
    container_name: sausage-store-backend-report
    environment:
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - sausage-store
  
  frontend:
    image: $CI_REGISTRY_IMAGE/sausage-frontend:${FRONTEND_VERSION}
    container_name: sausage-store-frontend
    ports:
      - "80:80"
    networks:
      - sausage-store
  
  vault:
    image: vault
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_SERVER: "http://127.0.0.1:8200"
      VAULT_ADDR: "http://127.0.0.1:8200"
    networks:
      - sausage-store

networks:
  sausage-store:
