version: "3.3"
services:

  backend:
    image: $CI_REGISTRY_IMAGE/sausage-backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: sausage-store-backend
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: ${PSQL_USER}
      SPRING_DATASOURCE_URL: ${PSQL_DATASOURCE}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_URL: ${VAULT_URL}
    networks:
      - sausage-store

  backend-report:
    image: $CI_REGISTRY_IMAGE/sausage-backend-report:latest
    build:
      context: backend-report
      dockerfile: Dockerfile
    container_name: sausage-store-backend-report
    restart: always
    environment:
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - sausage-store
  
  frontend:
    image: $CI_REGISTRY_IMAGE/sausage-frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: sausage-store-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - sausage-store
  
  vault:
    image: vault
    container_name: vault
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_SERVER: "http://127.0.0.1:8200"
      VAULT_ADDR: "http://127.0.0.1:8200"
    networks:
      - sausage-store

networks:
  sausage-store:
