version: "3.3"
services:

  backend:
    image: $CI_REGISTRY_IMAGE/sausage-backend:latest
    container_name: backend
    restart: always
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_URL: ${VAULT_URL}
      REPORT_PATH: /app/log/reports
      LOG_PATH: /app/log
    networks:
      - sausage-store

  backend-report:
    image: $CI_REGISTRY_IMAGE/sausage-backend-report:latest
    build:
      context: backend-report
      dockerfile: Dockerfile
    container_name: sausage-store-backend-report
    restart: always
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_URL: ${VAULT_URL}
    networks:
      - sausage-store
  
  frontend:
    image: $CI_REGISTRY_IMAGE/sausage-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store:
